---
version: "3"
services:
  vault1:
    container_name: vault1
    image: hashicorp/vault:1.12.3
    volumes:
      - ./vault1/logs:/vault/logs
      - ./vault1/storage:/vault/storage
      - ./vault1/config:/vault/config
    cap_add:
      - IPC_LOCK
    ports:
      - 8210:8200
      - 8211:8201
    command: ["server"]
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
  vault2:
    container_name: vault2
    image: hashicorp/vault:1.12.3
    volumes:
      - ./vault2/logs:/vault/logs
      - ./vault2/storage:/vault/storage
      - ./vault2/config:/vault/config
    cap_add:
      - IPC_LOCK
    ports:
      - 8220:8200
      - 8221:8201
    command: ["server"]
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200

